### ISSUE TITLE
Why use fixture scope="module"?

### ISSUE THREAD

**Issue by nils-werner** [kataev/pytest-grpc#14]
Right now, [the fixtures provided by `pytest-grpc`](https://github.com/kataev/pytest-grpc/blob/master/pytest_grpc/plugin.py#L98) are all set to `scope='module'`. This makes it hard/implossible to combine them with fixtures with the default `function` scope.

Is there a reason you chose this? I changed them to use the default value and everything still works fine.

**Comment by kataev** [comment]
I don't remember why, I think it happened so historically. At least it test faster.
I fink we can add some param for default session scope, and set it to `module` for backward compatibility
